---
title: "Day 4: Camp Cleanup"
output: html_notebook
---

```{r}
rm(list=ls())
```

```{r}
sekcje <- read.delim("input_cleanup_pairs", header = F, sep = ",", col.names = c("sekA", "sekB"))
head(sekcje)
```

```{r}
sekcje[,c("Amin", "Amax")] <- stri_split_fixed(sekcje$sekA, "-", simplify = T)
sekcje[,c("Bmin", "Bmax")] <- stri_split_fixed(sekcje$sekB, "-", simplify = T)

head(sekcje)
```
```{r}
sekcje$Amin <= sekcje$Bmin
```


```{r}
library(dplyr)
# ile par zawiera się w sobie
sekcje %>% 
  select(Amin, Bmin, Amax, Bmax) %>% 
  mutate_all(as.numeric) %>% 
  mutate(AwB = (Amin >= Bmin & Amax <= Bmax),
         BwA = (Amin <= Bmin & Amax >= Bmax),
         oba = AwB & BwA, lub = AwB | BwA) %>% 
  filter(lub == T) %>%
  nrow()
```


```{r}
# ile zadań zachodzi na siebie
sekcje %>% 
  select(Amin, Bmin, Amax, Bmax) %>% 
  mutate_all(as.numeric) %>% 
  mutate(AiB = Amax-Bmin,       # lewa na prawą
         BiA = Bmax-Amin) %>%   #prawa na lewą
  filter(AiB >= 0 & BiA >= 0) %>%
  nrow()

```



