---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```

```{r}
zapis <- readLines("terminal.txt", warn = F)
zapis <- tibble(zapis)
colnames(zapis) <- "line"
head(zapis)
```

```{r}
# $ ls ["cd ?+" | "$ cd .."]

list(zapis)
```

```{r}
cd <- function(path, dir = NA){
  if(any(is.na(dir))) return(path)
  if(any(dir == "..")) return (head(path, -1))
  return(c(path, paste0(tail(path,1), "/", dir)))
}

cd("c", cd("cos", cd("dalej")))
```

```{r}
paths <- zapis %>% 
  mutate(path = line %>% 
           str_extract("cd (.*)") %>% 
           str_remove("cd ")
         ) %>% 
  mutate(path = accumulate(path, cd)) %>% 
  unnest(path)

head(paths)
```

```{r}
paths %>% 
  filter(str_detect(line, "^[0-9]")) %>% 
  group_by(path) %>% 
  summarise(size = line %>% 
              str_extract("^[0-9]+") %>% 
              as.numeric() %>% 
              sum()
            ) %>% 
  arrange(-size) -> sizes

sizes
```

```{r}
sizes %>% 
  filter(size < 100000) %>% 
  pull(size) %>% 
  sum()
```

```{r}
total <- 7*10^7
required <- 30000000
used <- sizes[1,] %>% pull(size)

sizes %>% 
  filter(size >= (required - (total - used))) %>% 
  arrange(size)
```

