---
title: "Forrest"
output: html_notebook
---

```{r}
trees <- readLines("trees", warn=F)
n_row <- length(trees)
n_col <- nchar(trees[1])
trees <- stringi::stri_extract_all_regex(trees, "[0-9]", simplify = F)
trees <- matrix(lapply(trees, as.numeric) |> unlist(), n_row, n_col, byrow = T)

head(trees)
```

```{r}
trees_dif <- matrix(0, nrow = n_row, ncol = n_col)

trees_dif[2,2] <- min(trees[1:3,1:3][c(2,4,6,8)] - trees[2,2])
trees_dif[2,3] <- min(trees[1:3,2:4][c(2,4,6,8)] - trees[2,3])

for(w in 2:(n_row-1)){
  for(k in 2:(n_col-1)){
     trees_dif[w,k] <- min(trees[w,k] - trees[(w-1):(w+1),(k-1):(k+1)][c(2,4,6,8)])
  }
}

```


```{r}
# looking at whole row 
see <- function(trees) {
  trees.seen <- matrix(0, n_row, n_col)
  tree.count <- 0
  
  for (w in 2:(n_row - 1)) {
    start.tree <- trees[w, 1]
    for (k in 2:(n_col - 1)) {
      if (start.tree < trees[w, k]) {
        trees.seen[w, k] <- 1
        tree.count <- tree.count + 1
        start.tree <- trees[w, k]
        #print(paste0("w", w, ": ", tree.count))
        next
      }
    }
  }
  #print(tree.count)
  return(trees.seen)
}
```


```{r}
sum(
  # see on four sides
  (see(trees) + 
  see(t(trees)) |> t() + 
  see(trees[,n_col:1])[,n_col:1] +
  see(t(trees)[,n_col:1])[,n_col:1] |> t() ) > 0 ) +
  2 * n_row + (2 * (n_row - 2)) # adding trees from the edges

```


# Part Two

```{r}
testuj <- function(zbior_drzew, debug = F) {
  if(length(zbior_drzew)==1){return(0)}
  ok <- 0
  if (debug) {print(zbior_drzew)}
  drzewo <- zbior_drzew[1]
  for (i in 2:length(zbior_drzew)) {
    
    if(debug){print(paste("drzewo:", drzewo, "drugie:",zbior_drzew[i]))}
    
    if (drzewo == zbior_drzew[i]) {
      #rowne
      ok <- ok + 1
      return(ok)
      } else if(drzewo < zbior_drzew[i]) {
      #mniejsze
      ok <- ok + 1
      return(ok)
      } else if(drzewo > zbior_drzew[i]){
      #większe
      #drzewo <- zbior_drzew[i]
      ok <- ok + 1
      }
    if (debug) {  print(paste("i:", i, "wynik:",ok))}
    }
  return(ok)
}

#######
testuj(4:1,T)
testuj(c(4,1:3),T)
testuj(c(3,3:1))
```


```{r}
# best tree for treehouse
a <- b <- c <- d <- 0
oceny <- matrix(0,n_row,n_col)

for(k in 1:n_col){
  for(w in 1:n_row){
    #sprawdź w lewo
    a <- testuj(trees[w,(k:1)])
    #sprawdź w w prawo
    b <- testuj(trees[w,(k:n_col)])
    #sprawdź w górę
    c <- testuj(trees[w:1,k])
    #sprawdź w dół
    d <- testuj(trees[(w:n_row),k])
    oceny[w,k] <- a*b*c*d
  }
}
oceny %>% max


```


