---
title: "Day 4: Camp Cleanup"
output: html_notebook
---

```{r}
sekcje <- read.delim("input_cleanup_pairs.txt", header = F, sep = ",", col.names = c("sekA", "sekB"))
head(sekcje)
```
```{r}
sekcje[,c("Amin", "Amax")] <- stri_split_fixed(sekcje$sekA, "-", simplify = T)
sekcje[,c("Bmin", "Bmax")] <- stri_split_fixed(sekcje$sekB, "-", simplify = T)

head(sekcje)
```
```{r}
sekcje$Amin <= sekcje$Bmin
```


```{r}
library(dplyr)
# ile par zawiera się w sobie
sekcje %>% 
  select(Amin, Bmin, Amax, Bmax) %>% 
  mutate_all(as.numeric) %>% 
  mutate(AwB = (Amin >= Bmin & Amax <= Bmax),
         BwA = (Amin <= Bmin & Amax >= Bmax),
         oba = AwB & BwA, lub = AwB | BwA) %>% 
  filter(lub == T) %>%
  nrow()
```


```{r}
# ile zadań zachodzi na siebie
sekcje %>% 
  select(Amin, Bmin, Amax, Bmax) %>% 
  mutate_all(as.numeric) %>% 
  mutate(AiB = Amax-Bmin,       # lewa na prawą
         BiA = Bmax-Amin) %>%   #prawa na lewą
  filter(AiB >= 0 & BiA >= 0) %>%
  nrow()

```


```{r}
# rozwiązanie z internetu

seq_test <- function(x, part=1){
  x <- as.numeric(x)
  a <- seq(x[1], x[2])
  b <- seq(x[3], x[4])

  lab <- length(dplyr::intersect (a,b))

  if(part==1){
    (length(a)== lab | length(b) == lab )
  } else if(part==2){
    lab>0
  }
}

sapply( strsplit (readLines ( "input_cleanup_pairs.txt", warn = F), "\\-|," ) , seq_test , part = 2) |> sum()

```

