---
title: "Day 2"
output: html_notebook
---

https://adventofcode.com

```{r}
df <- read.delim("./input2", header = F, sep = " ")
```

```{r}
#strategy
A <- "rock"       #X 1
B <- "paper"      #Y 2
C <- "scissors"   #Z 3

# points
A.X <- 4  #tie   3 + 1
A.Y <- 8  #win   6 + 2
A.Z <- 3  #lose  0 + 3

B.X <- 1  #lose  0 + 1
B.Y <- 5  #tie   3 + 2
B.Z <- 9  #win   6 + 3

C.X <- 7  #win   6 + 1
C.Y <- 2  #lose  0 + 2
C.Z <- 6  #tie   3 + 3
```


```{r}
# punktacja z wybór + punkty za stan meczu
scores <- matrix(rep(1:3,3),3,3, byrow=T) + matrix(c(3,6,0,0,3,6,6,0,3), 3,3, byrow = T)
colnames(scores) <- c("X","Y","Z")
rownames(scores) <- c("A","B","C")
```

```{r}
table(df) |> as.matrix() * scores -> scores_table
scores_table
```

```{r}
as.vector(scores_table) |> sum()
```

scores <- matrix(rep(1:3,3),3,3, byrow=T) + matrix(c(3,6,0,0,3,6,6,0,3), 3,3, byrow = T)

```{r}
# druga strategia
# punktacja z wybór + punkty za stan meczu
scores <- matrix(c(3,1,2,1,2,3,2,3,1),3,3, byrow=T) + matrix(rep(c(0,3,6),3), 3,3, byrow = T)
colnames(scores) <- c("X","Y","Z")
rownames(scores) <- c("A","B","C")
```

```{r}
table(df) |> as.matrix() * scores -> scores_table
scores_table
```

```{r}
as.vector(scores_table) |> sum()
```

